# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_page_game.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 695)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 831, 651))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/_8cafa14e-b673-4721-a538-fd13d0d598bd.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Play_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Play_btn.setGeometry(QtCore.QRect(390, 550, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Play_btn.setFont(font)
        self.Play_btn.setFlat(True)
        self.Play_btn.setObjectName("Play_btn")

        self.Play_btn.clicked.connect(self.play_game)

        self.About_btn = QtWidgets.QPushButton(self.centralwidget)
        self.About_btn.setGeometry(QtCore.QRect(120, 550, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.About_btn.setFont(font)
        self.About_btn.setCheckable(False)
        self.About_btn.setAutoDefault(False)
        self.About_btn.setDefault(False)
        self.About_btn.setFlat(True)
        self.About_btn.setObjectName("About_btn")

        self.About_btn.clicked.connect(self.about_page)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(650, 560, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 200, 511, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 825, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def play_game(self):
        os.system("python a_main.py")
    def about_page(self):
        os.system("python About_page.py")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Play_btn.setText(_translate("MainWindow", "Play"))
        self.About_btn.setText(_translate("MainWindow", "About"))
        self.pushButton.setText(_translate("MainWindow", "Auto play"))
        self.label_2.setText(_translate("MainWindow", "CHESS BATTLE "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
